### ISSUE TITLE
Bug: In the cards for the posts, the wrong name is displayed.

### ISSUE THREAD

**Issue by superDeano** [twatter-soen341/Twatter#102]
Problem:

Each card which displays a twat (post), is supposed to display the first name of the current user in the /posts page.  Somehow it does not and just displays 'NAME NAME' instead.

Steps to reproduce:

1. Log into Twatter
2. Start Posting some twats (posts).

Expected Result:

The cards displaying the actual twats show the actual first name of the current user.

Actual Result:

The cards display 'NAME NAME' instead.

**Comment by a-paggabao** [comment]
Resolved; displays firstName and lastName.
Will be official after merge with updated post services.

**Comment by a-paggabao** [comment]
Completed. Refer to #103
