### ISSUE TITLE
Bug: Scroll bar in Create Post Dialog is not functioning as expected.

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#130]
## Problem
The scroll bar does not scroll the text upwards. 
It seems to be linked to the div instead of the textarea.

## Steps to Reproduce
1. Open create post dialog
2. Write or insert multiple lines of text.
3. Try to scroll up to the first line.

## Expected Result
You can scroll up and down

## Actual Result
You cannot scroll up and you can only see part of your text.

### Note
If you use the blinking text cursor higher, you can see the previous written text.

### Possible Resolution
Add a character limit.

**Comment by paulMoose** [comment]
Fixed by adding a character limit and removing the scroll.
