### ISSUE TITLE
Acceptance Test for User Story #25

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#161]
## Acceptance Test
| User Story | `#25` |
| --: | :--|
| **Test Priority** | NORMAL |
| **Test Title**    | User can create a post |
| **Description**   | User can write some content and save it as a new post on Twatter. |
| **Tester Name**   | Alexandria Paggabao |

## Test Result
| Step | Test Step | Test Data | Expected Results | Acutal Results | Status | Notes |
| :--: | :-- | :-- | :-- | :-- | :--: | :-- |
| 1 | Navigate to home page by clicking the home icon. |  | Route to home page |  |  |  | 
| 2 | Click on the textbox under "Create Twat". |  | Display dialog box to create "Twat" |  |  |  |
| 3 | Write some content. |  | Content is typed in textarea |  |  |  |
| 4 | Click "TWAT" to post. |  | Dialog box closes and the post is added in home page and user's profile. |  |  |  |

_**Step**_ *&* _**Test Step**_ *should be filled in description. The rest should be filled and reposted as comment.*

**Comment by a-paggabao** [comment]
## Test Result
| Step | Test Step | Test Data | Expected Results | Acutal Results | Status | Notes |
| :--: | :-- | :-- | :-- | :-- | :--: | :-- |
| 1 | Navigate to home page by clicking the home icon. |  | Route to home page | Route to home page | Pass |  | 
| 2 | Click on the textbox under "Create Twat". |  | Display dialog box to create "Twat" | Display dialog box to create "Twat" | Pass |  |
| 3 | Write some content. | "Roast me!"  | Content is typed in textarea | Content is typed in textarea | Pass |  |
| 4 | Click "TWAT" to post. | "Roast me!" | Dialog box closes and the post is added in home page and user's profile. | Dialog box closes and the post is added in home page and user's profile. | Pass | User stor #25 Passed Accepance test #161 |

**Comment by paulMoose** [comment]
Acceptance Test Completed.
