### ISSUE TITLE
Acceptance Test for User Story #81

### ISSUE THREAD

**Issue by paulMoose** [twatter-soen341/Twatter#176]
## Acceptance Test
| User Story | `#81` |
| --: | :--|
| **Test Priority**    | NORMAL |
| **Test Title**         | User can delete a post. |
| **Description**     | User can delete their own posts. |
| **Tester Name**   | Alexandria Paggabao |

## Test Result
| Step | Test Step | Test Data | Expected Results | Acutal Results | Status | Notes |
| :--: | :-- | :-- | :-- | :-- | :--: | :-- |
| 1 | Navigate to home page by clicking the home icon.  |  | Route to home page |  |  | |
| 2 | Click on the delete icon on one of your posts. |  | Deletes post and removes post from home page and user's profile. |  |  |  |

_**Step**_ *&* _**Test Step**_ *should be filled in description. The rest should be filled and reposted as comment.*

**Comment by a-paggabao** [comment]
## Test Result
| Step | Test Step | Test Data | Expected Results | Actual Results | Status | Notes |
| :--: | :-- | :-- | :-- | :-- | :--: | :-- |
| 1 | Navigate to home page by clicking the home icon.  |  | Route to home page | Route to home page | Pass  | |
| 2 | Click on the delete icon on one of your posts. |  | Deletes post and removes post from home page and user's profile. | Deletes post and removes post from home page and user's profile. | Pass  | User story #81 passed Acceptance test #176 |
