### ISSUE TITLE
As a User I want to be notified, if someone commented on my post.

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#189]
## Description
User should be notified if they have a new comment on any of their posts. Once viewed, the notification will disappear. 

## Task Breakdown
- [ ] Update notification to be notified for new comments. (#190)
- [ ] Display preview of posts with new comments on notification icon. (#191) 

## Risk: Low

**Comment by paulMoose** [comment]
Will no longer implement this user story; approved by the TA.
