### ISSUE TITLE
As a User, I want to update my user profile avatar so that I can personalize my profile.

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#195]
## Description
User can save a photo as their avatar. User has the choice to choose from set of default avatars or their own import.

## Task Breakdown
- [ ] Modify User profile UI to add button/icon to change profile avatar. (#issue)
- [ ] Display a set of default avatars (#issue)

**Comment by paulMoose** [comment]
Will no longer implement this user story; approved by TA.
