### ISSUE TITLE
Create user authentication services (login, logout, signup)

### ISSUE THREAD

**Issue by paulMoose** [twatter-soen341/Twatter#2]
We could use JSON Web Tokens or other ways to authenticate the user.
- [x] mongoose data model of a "User"
- [x] routes for authentification
- [x] Services & Interceptor on the front end to use the token
- [x] Route Guard in angular
- [ ] Tests
- [x] Documentation

**Comment by paulMoose** [comment]
We could use JSON Web Tokens or other ways to authenticate the user.

**Comment by Nichita-Hariton** [comment]
We can also use passport.js as an alternative

**Comment by paulMoose** [comment]
I will close this issue since it is a duplicate of #35.
