### ISSUE TITLE
The system should use a tool that generates a bug report.

### ISSUE THREAD

**Issue by Nichita-Hariton** [twatter-soen341/Twatter#220]
## Description
In order to follow a professional code implementation patterns, the system should adopt a way to find bugs in the codebase based on bug patterns. The system could implement JSLINT or any other softwares

## Task Breakdown
- [x] discuss with team of the appropriate software that the system should use

**Comment by a-paggabao** [comment]
Team decided to implement JSLint.

**Comment by a-paggabao** [comment]
Done. Reviewed with the team.
