### ISSUE TITLE
BUG: When creating a new account and logging in the same browser, the new user can see the twats of the previous user.

### ISSUE THREAD

**Issue by superDeano** [twatter-soen341/Twatter#232]
**Problem**
When a user logs out of his current account, creates a new account, then logs into the newly created one, he can see the twats from his previous account.

**Steps to Reproduce**

1. Log into an account and create and post some twats

2. Log out and create a new account.

3. Log in with the newly created account. 

See image below for more info

![Screen Shot 2019-03-25 at 7 28 01 PM](https://user-images.githubusercontent.com/33161860/54960809-977dab80-4f34-11e9-8329-82f70345ab3c.png)

**Comment by superDeano** [comment]
Bugs happening to me on Brave, Firefox and Safari browsers.

**Comment by paulMoose** [comment]
Narra fixed this.
