### ISSUE TITLE
As a user, I want to like a Tweet so that I can show my appreciation to the poster.

### ISSUE THREAD

**Issue by tarekait1996** [twatter-soen341/Twatter#38]
## Description
The system should allow an existing user to like a post from another user. The user will click a button and it will change the color to indicate that the user liked the post. The user should be able to like the posts from all Twatter community.

## Task Breakdown
- [x] Design UI for liking button (#54)
- [x] Update post model to support liking a tweet (#55)
- [ ] Create Tests (#56)

## Risk: Low

**Comment by narrapangan** [comment]
sadjfslakdjf
