### ISSUE TITLE
As a User, I would like to have my own profile page so that I can see all of the tweets I have written so far.

### ISSUE THREAD

**Issue by tarekait1996** [twatter-soen341/Twatter#39]
## Description
The profile page will show the name, last name and the email of the user. On this page will be all of the posts that have been written by the named user. The list of users that the current user is following and the list of the current user's followers will also be displayed.

## Task Breakdown

- [x] Design UI for Profile (#57) 
- [x] Filter tweets to retrieve by User (#58)
- [x] Tests (#59)

## Risk: Medium

**Comment by superDeano** [comment]
Would that be on the profile page ?

**Comment by jayohanna** [comment]
Me and Viveka want to work on the profile page

**Comment by tarekait1996** [comment]
This does not seem to be one of the three core-feature for sprint 2 so I think we should leave it for sprint 3 and eventually add this twatline to the profile page.

**Comment by EtienneBerube** [comment]
Any update on this User Story?
