### ISSUE TITLE
Design UI for Profile.

### ISSUE THREAD

**Issue by Nichita-Hariton** [twatter-soen341/Twatter#57]

**Comment by viveanban** [comment]
Small features unique to the profile page:
1 - A header with user information: icon + username + user info
2 - Container with scrollable twats.
3 - Sticky header (meaning it stays at the top when we scroll down the twats)
4 - Scroll up to see the logo/home/default header with the search bar.

Sub-tasks:
[] Static header with user info
[] Implement feature to scroll up to see the home header
[] Implement scroll back to top button
[] Display the user's posts

![profile_proto](https://user-images.githubusercontent.com/32105523/52458028-f032e980-2b2a-11e9-9d59-98af077bac37.png)

**Comment by jayohanna** [comment]
Profile layout will be like this instead, since there is a default header
Also more space for user information in a sidebar vs header

![image](https://user-images.githubusercontent.com/33985435/52544138-d4bf1d00-2d7c-11e9-8f3a-d1e5f25824b0.png)
